import React, { useEffect, useState } from 'react';
import { CheckCircle2, RefreshCw, ShieldCheck, XCircle } from 'lucide-react';
import type { JobPosting } from '../../types';
import { approvePendingJob, loadPendingApprovalJobs, rejectPendingJob } from '../../services/adminJobs';

export function AdminJobsScreen({ onLogout }: { onLogout:()=>void }) {
  const [jobs,setJobs]=useState<JobPosting[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [busy,setBusy]=useState('');
  const load=async()=>{setLoading(true);setError('');try{setJobs(await loadPendingApprovalJobs())}catch(e){setError(e instanceof Error?e.message:'Unable to load approvals.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const approve=async(id:string)=>{setBusy(id);try{await approvePendingJob(id);setJobs(v=>v.filter(j=>j.id!==id))}catch(e){setError(e instanceof Error?e.message:'Approval failed.')}finally{setBusy('')}};
  const reject=async(id:string)=>{const reason=window.prompt('Optional rejection reason:')||'';setBusy(id);try{await rejectPendingJob(id,reason);setJobs(v=>v.filter(j=>j.id!==id))}catch(e){setError(e instanceof Error?e.message:'Rejection failed.')}finally{setBusy('')}};
  return <div className="min-h-screen bg-[#fdf8f8]"><header className="h-16 px-5 flex items-center justify-between bg-white border-b border-[#e0bec6]"><div className="flex items-center gap-2"><ShieldCheck className="text-[#8e004b]"/><h1 className="font-extrabold">Admin · Pending Approvals</h1></div><button onClick={onLogout} className="text-xs font-bold text-rose-700">Sign out</button></header>
    <main className="max-w-5xl mx-auto p-5 md:p-8"><div className="flex justify-between items-center mb-6"><div><h2 className="text-2xl font-extrabold">Pending Job Posts</h2><p className="text-sm text-[#594047]">Review full details before publishing.</p></div><button onClick={()=>void load()} className="p-2 rounded-full bg-white border"><RefreshCw className={loading?'animate-spin':''}/></button></div>
    {error&&<p className="mb-4 bg-rose-50 border border-rose-200 rounded-xl p-3 text-sm text-rose-700">{error}</p>}
    {loading?<p>Loading approvals…</p>:jobs.length===0?<div className="bg-white rounded-2xl border p-10 text-center"><CheckCircle2 className="mx-auto text-emerald-600 w-10 h-10"/><p className="mt-3 font-bold">No pending approvals</p></div>:<div className="space-y-4">{jobs.map(job=><article key={job.id} className="bg-white rounded-2xl border border-[#e0bec6] p-5 shadow-sm"><div className="flex flex-col md:flex-row md:justify-between gap-4"><div><span className="inline-block bg-amber-100 text-amber-900 px-2 py-1 rounded-full text-[11px] font-bold">Pending Approval</span><h3 className="text-xl font-bold mt-2">{job.title}</h3><p className="text-sm text-[#594047]">{job.salonName} · {job.location} · {job.salary}</p><p className="text-sm mt-3 whitespace-pre-wrap">{job.description}</p>{job.requirements.length>0&&<p className="text-xs mt-3"><b>Requirements:</b> {job.requirements.join(', ')}</p>}</div><div className="flex md:flex-col gap-2 shrink-0"><button disabled={busy===job.id} onClick={()=>void approve(job.id)} className="bg-emerald-600 text-white rounded-full px-5 py-2 text-sm font-bold flex gap-1 items-center"><CheckCircle2 className="w-4 h-4"/>Approve</button><button disabled={busy===job.id} onClick={()=>void reject(job.id)} className="bg-rose-50 text-rose-700 border border-rose-200 rounded-full px-5 py-2 text-sm font-bold flex gap-1 items-center"><XCircle className="w-4 h-4"/>Reject</button></div></div></article>)}</div>}
    </main></div>;
}
