-- ===========================================================================
-- Nexora Jobs: frontend/backend integration hardening
--
-- The audit compared every procedure the schema exposes with what the browser
-- actually calls, and checked the storage policies against what the UI reads.
-- Four things came out of it.
--
--   1. Candidate search had no full-text capability at all: `search_job_candidates`
--      could filter by city and by one skill, but an employer searching for
--      "balayage colourist" had nothing to hit. -> a generated tsvector column
--      with a GIN index, and the RPC extended with a text query, an experience
--      floor and relevance ordering.
--
--   2. Storage policies covered the applicant's own files and their resumes, but
--      three legitimate readers were missing: an administrator reviewing an
--      employer verification, an administrator answering a support ticket with an
--      attachment, and a salon member looking at the avatar of somebody who
--      applied to their posting. -> three read policies.
--
--   3. `publish_job` was an unguarded-looking alias for `approve_job` with no
--      caller anywhere in the application. It is kept for compatibility but no
--      longer reachable by clients: the admin path is `approve_job`.
--
--   4. Every other RPC was verified to carry an authorization guard; that check
--      is now a permanent invariant in the test suite (see test:db section 11)
--      instead of a one-off audit, so a future procedure cannot ship without one.
--
-- Idempotent. Apply after the other jobs migrations.
-- ===========================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1. Candidate search: full-text over the parts of a profile an employer
--    searches by, maintained by the database rather than by the client.
-- ---------------------------------------------------------------------------

alter table public.job_seeker_profiles
  add column if not exists search_vector tsvector
  generated always as (
    to_tsvector('english',
      coalesce(headline, '') || ' ' || coalesce(bio, '') || ' ' || coalesce(city, '') || ' ' || coalesce(state, ''))
  ) stored;

create index if not exists job_candidate_search_idx
  on public.job_seeker_profiles using gin (search_vector);

-- Experience is the second thing employers filter on, and it is filtered for
-- rows that are already narrowed to the opted-in visibility.
create index if not exists job_candidate_experience_idx
  on public.job_seeker_profiles (profile_visibility, total_experience_months desc);

comment on column public.job_seeker_profiles.search_vector is
  'Full-text index over headline, bio, city and state. Generated by the database so it can never drift from the profile text.';

-- The parameters the application already sends keep their names and defaults;
-- new ones are appended so existing calls keep working unchanged.
create or replace function public.search_job_candidates(
  p_city text default null,
  p_skill_id uuid default null,
  p_limit integer default 20,
  p_offset integer default 0,
  p_query text default null,
  p_min_experience_months integer default null
)
returns table(candidate_id uuid, user_id uuid, full_name text, avatar_path text, headline text, bio text,
              city text, state text, experience_level text, total_experience_months integer,
              expected_salary_min numeric, expected_salary_max numeric, available_from date,
              open_to_relocation boolean, skills text[])
language plpgsql
stable
security definer
set search_path = ''
as $fn$
declare
  query_ts tsquery;
begin
  perform public.job_assert_authenticated();
  if public.job_current_role() not in ('employer', 'admin')
     or not (
       public.job_is_admin()
       or exists (
         select 1 from public.job_salon_members m
         where m.user_id = (select auth.uid()) and m.status = 'active'
       )
     ) then
    raise exception using errcode='42501', message='ROLE_NOT_ALLOWED';
  end if;

  -- websearch_to_tsquery accepts what a person types ("senior colourist -junior")
  -- and never raises on odd input.
  if p_query is not null and trim(p_query) <> '' then
    query_ts := websearch_to_tsquery('english', trim(p_query));
  end if;

  return query
  select
    c.id, c.user_id, p.full_name, p.avatar_path, c.headline, c.bio, c.city, c.state,
    c.experience_level, c.total_experience_months, c.expected_salary_min,
    c.expected_salary_max, c.available_from, c.open_to_relocation,
    coalesce(array_agg(distinct sk.name) filter (where sk.id is not null), '{}'::text[])
  from public.job_seeker_profiles c
  join public.profiles p on p.id = c.user_id
  left join public.job_candidate_skills cs on cs.candidate_id = c.id
  left join public.job_skills sk on sk.id = cs.skill_id
  where c.profile_visibility = 'employers'
    and p.is_active = true
    and (p_city is null or lower(c.city) = lower(p_city))
    and (p_min_experience_months is null or c.total_experience_months >= p_min_experience_months)
    and (query_ts is null or c.search_vector @@ query_ts)
    and (
      p_skill_id is null or exists (
        select 1 from public.job_candidate_skills match_skill
        where match_skill.candidate_id = c.id and match_skill.skill_id = p_skill_id
      )
    )
  group by c.id, p.id, p.full_name, p.avatar_path
  order by
    case when query_ts is null then 0 else ts_rank(c.search_vector, query_ts) end desc,
    c.total_experience_months desc,
    c.id
  limit greatest(coalesce(p_limit, 20), 1)
  offset greatest(coalesce(p_offset, 0), 0);
end
$fn$;

revoke execute on function public.search_job_candidates(text, uuid, integer, integer, text, integer) from public, anon;
grant execute on function public.search_job_candidates(text, uuid, integer, integer, text, integer) to authenticated;

comment on function public.search_job_candidates(text, uuid, integer, integer, text, integer) is
  'Employer talent search. Only profiles that opted into employer visibility are returned, ordered by full-text relevance when a query is given.';

-- ---------------------------------------------------------------------------
-- 2. Storage: the readers that were missing. Every policy is scoped to a row
--    the caller can already prove a relationship with — an administrator, or a
--    salon member acting on their own posting — so no file becomes public.
-- ---------------------------------------------------------------------------

-- An administrator reviews employer verification documents (review_employer_verification
-- is admin-only, but the file behind it was unreadable to them).
drop policy if exists job_verification_admin_read on storage.objects;
create policy job_verification_admin_read
on storage.objects for select to authenticated
using (bucket_id = 'employer-verification' and public.job_is_admin());

-- Support attachments: the ticket owner and the administrator handling it.
drop policy if exists job_support_admin_read on storage.objects;
create policy job_support_admin_read
on storage.objects for select to authenticated
using (bucket_id = 'job-support-attachments' and public.job_is_admin());

-- Applicant avatar/photo: a salon member may read the profile media of somebody
-- who applied to one of that salon's postings — the same relationship that
-- already lets them read the applicant's resume.
drop policy if exists job_profile_media_applicant_read on storage.objects;
create policy job_profile_media_applicant_read
on storage.objects for select to authenticated
using (
  bucket_id = 'job-profile-media'
  and (storage.foldername(name))[1] ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
  and exists (
    select 1
    from public.job_applications a
    join public.job_posts j on j.id = a.job_id
    where a.candidate_user_id = ((storage.foldername(name))[1])::uuid
      and public.job_is_active_salon_member(j.salon_id)
  )
);

-- ---------------------------------------------------------------------------
-- 3. Least privilege on the moderation surface.
--
--    `publish_job` only forwards to `approve_job`, which does the admin check
--    itself, so it was not exploitable — but it is a second, undocumented name
--    for a privileged action and nothing calls it. Clients lose access; the
--    admin path stays `approve_job`.
-- ---------------------------------------------------------------------------

revoke execute on function public.publish_job(uuid) from public, anon, authenticated;

comment on function public.publish_job(uuid) is
  'Deprecated alias of approve_job(). No client may execute it; admin approval uses approve_job().';

comment on function public.job_location_distance_m(numeric, numeric, numeric, numeric) is
  'Pure distance arithmetic (haversine). Reads no table and takes no identifiers, so it needs no authorization guard.';

comment on function public.pause_job(uuid) is
  'Employer lifecycle action: approved -> paused, salon members only.';
comment on function public.resume_job(uuid) is
  'Employer lifecycle action: paused -> approved, salon members only.';
comment on function public.submit_job_for_approval(uuid) is
  'Employer lifecycle action: draft/rejected -> pending_approval, salon members only. This is the only way a posting reaches the admin queue.';

commit;
